#!/usr/bin/env bash
# write Indefinitely "I am alive" in the file/tmp/my_process.
#   Waiting Two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
